export const NEW_ADOPT_REQUEST = "NEW_ADOPT_REQUEST";
export const NEW_ADOPT_SUCCESS = "NEW_ADOPT_SUCCESS";
export const NEW_ADOPT_FAIL = "NEW_ADOPT_FAIL";
export const NEW_ADOPT_RESET = "NEW_ADOPT_RESET";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PET_ADOPT_REQUEST = "PET_ADOPT_REQUEST";
export const PET_ADOPT_SUCCESS = "PET_ADOPT_SUCCESS";
export const PET_ADOPT_FAIL = "PET_ADOPT_FAIL";

export const MY_REQUEST_REQUEST = "MY_REQUEST_REQUEST";
export const MY_REQUEST_SUCCESS = "MY_REQUEST_SUCCESS";
export const MY_REQUEST_FAIL = "MY_REQUEST_FAIL";
export const MY_REQUEST_RESET = "MY_REQUEST_RESET";

export const PET_REQUEST_REQUEST = "PET_REQUEST_REQUEST";
export const PET_REQUEST_SUCCESS = "PET_REQUEST_SUCCESS";
export const PET_REQUEST_FAIL = "PET_REQUEST_FAIL";
export const PET_REQUEST_RESET = "PET_REQUEST_RESET";
