export const ALL_PET_REQUEST = "ALL_PET_REQUEST";
export const ALL_PET_SUCCESS = "ALL_PET_SUCCESS";
export const ALL_PET_FAIL = "ALL_PET_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PET_DETAILS_REQUEST = "PET_DETAILS_REQUEST";
export const PET_DETAILS_SUCCESS = "PET_DETAILS_SUCCESS";
export const PET_DETAILS_FAIL = "PET_DETAILS_FAIL";

export const NEW_PET_REQUEST = "NEW_PET_REQUEST";
export const NEW_PET_SUCCESS = "NEW_PET_SUCCESS";
export const NEW_PET_FAIL = "NEW_PET_FAIL";
export const NEW_PET_RESET = "NEW_PET_RESET";

export const MY_PETS_REQUEST = "MY_PETS_REQUEST";
export const MY_PETS_SUCCESS = "MY_PETS_SUCCESS";
export const MY_PETS_FAIL = "MY_PETS_FAIL";

export const DELETE_PET_REQUEST = "DELETE_PET_REQUEST";
export const DELETE_PET_SUCCESS = "DELETE_PET_SUCCESS";
export const DELETE_PET_FAIL = "DELETE_PET_FAIL";
export const DELETE_PET_RESET = "DELETE_PET_RESET";
